#!/bin/bash

stream="mplayer -quiet http://live-aacplus-64.kexp.org/kexp64.aac"

case "$1" in
	--start)
		eval $stream &>/var/tmp/mplayer.log &disown
		;;
	--stop)
		eval "pkill mplayer"
		exit 0
                ;;
	--np)
		line=`cat /var/tmp/mplayer.log | grep -o "StreamTitle='\K[^']+"`

		case "$param" in
		  *[!\ ]*) printf "now playing:\n\n $line";;
		  *) printf "now playing:\n\n ¯\_(ツ)_/¯ \n";;
		esac		
		;;
esac
